//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GenderId { get; set; }
        public string Info { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
